### ISSUE TITLE
Source code for NVIDIA Volumetric Lighting?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/FaceWorks#1]
Hi thanks for Faceworks release..
but where is NVIDIA Volumetric Lighting release?
press note says source code for NVIDIA Volumetric Lighting and NVIDIA’s FaceWorks demo is available today..
thanks..

**Comment by NvPhysX** [comment]
Sorry, just a few last minute delays. It will be up in the next 24-72 hours. Please check back at developer.nvidia.com for details.


--Mike

________________________________
