### ISSUE TITLE
FaceWorks Binaries?

### ISSUE THREAD

**Issue by MichaelEmouse** [NVIDIAGameWorks/FaceWorks#2]
I'll admit the error may well be mine but I'm having difficulty finding the precompiled binaries for FaceWorks. The "Contents of the Archive" section mentions in samples/bin/ but the actual samples folder doesn't have them.

**Comment by NvPhysX** [comment]
?I think that's an error, you have to compile it.


--Mike

________________________________

**Comment by mfoco** [comment]
I've removed the references to "bin" directory and changed the wording from "archive" to "repository".
Thank you Michael for pointing this out.
