### ISSUE TITLE
Licence confusion

### ISSUE THREAD

**Issue by KeepItOneHundred** [NVIDIAGameWorks/FaceWorks#3]
The prelude licence on each source file is simply 3-Clause BSD verbatim, but the licence in the root of the repo is completely different and more restrictive.

I'm getting mixed messages here - are the source files released under standard BSD or not?

**Comment by NvPhysX** [comment]
Hi,?


I'll take another look at it. The intention was to release FaceWorks with the same license that applies to the NVIDIA graphics samples.


--Mike

________________________________
